# Generated by Django 3.2.8 on 2021-10-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('name_mm', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
            ],
        ),
    ]
